services:
  neodash:
    container_name: neodash
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    environment:
      - NGINX_PORT=5005
      - ssoEnabled=true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.neodash.entrypoints=https"
      - "traefik.http.routers.neodash.rule=Host(`neodash.devcraft.team`)"
      - "traefik.http.routers.neodash.tls=true"
      - "traefik.http.services.neodash.loadbalancer.server.port=5005"
      - "traefik.http.routers.neodash.tls.certresolver=cloudflare"

networks:
  proxy:
    external: true
